
services:
  rabbit:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  order-cache-replica:
    image:  hazelcast/hazelcast:5.5.0
    volumes:
    - type: "bind"
      source: "./hazelcast"
      target: "/opt/hazelcast/config_ext"
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast-order.xml"

  reservation-cache-replica:
    image:  hazelcast/hazelcast:5.5.0
    volumes:
      - type: "bind"
        source: "./hazelcast"
        target: "/opt/hazelcast/config_ext"
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast-reservation.xml"

  reservation-service:
    build: ./eda-reservation-service
    image: eda-reservation-service:1
    restart: always
    depends_on:
      - rabbit
      - reservation-cache-replica
    environment:
      server.port: 80
      spring.rabbitmq.host: rabbit

  payment-service:
    build: ./eda-payment-service
    image: eda-payment-service:1
    restart: always
    depends_on:
    - rabbit
    environment:
      server.port: 80
      spring.rabbitmq.host: rabbit
      chaos.monkey.assaults.level: 10 # attack each 10th request. the default is 5
      chaos_monkey_enabled:

  order-service:
    build: ./eda-order-service
    image: eda-order-service:1
    restart: always
    ports:
    - "8080:80"
    depends_on:
    - rabbit
    - order-cache-replica
    - reservation-service
    - payment-service
    environment:
      server.port: 80
      spring.rabbitmq.host: rabbit
      app_services_payment: http://payment-service
      app_services_reservation: http://reservation-service

