# chaos_monkey_enabled will pick up the value from the
# shell when 'docker-compose up' is executed

version: '3.2'
services:
  rabbit:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  order-cache-replica:
    image:  hazelcast/hazelcast
    volumes:
    - type: "bind"
      source: "./hazelcast"
      target: "/opt/hazelcast/config_ext"
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast-order.xml"

  reservation-cache-replica:
    image:  hazelcast/hazelcast
    volumes:
      - type: "bind"
        source: "./hazelcast"
        target: "/opt/hazelcast/config_ext"
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast-reservation.xml"

  service-registry:
    build: ./eda-service-registry
    image: eda-service-registry:1
    restart: always
    ports:
      - "8761:8761"

  reservation-service:
    build: ./eda-reservation-service
    image: eda-reservation-service:1
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - rabbit
      - service-registry
      - reservation-cache-replica
    environment:
      spring.rabbitmq.host: rabbit
      eureka.instance.hostname: service-registry
      chaos_monkey_enabled:

  payment-service:
    build: ./eda-payment-service
    image: eda-payment-service:1
    restart: always
    ports:
    - "8082:8080"
    depends_on:
    - rabbit
    - service-registry
    environment:
      spring.rabbitmq.host: rabbit
      eureka.instance.hostname: service-registry
      chaos_monkey_enabled:

  order-service:
    build: ./eda-order-service
    image: eda-order-service:1
    restart: always
    ports:
    - "8080:8080"
    depends_on:
    - rabbit
    - service-registry
    - order-cache-replica
    - reservation-service
    - payment-service
    environment:
      spring.rabbitmq.host: rabbit
      eureka.instance.hostname: service-registry
      chaos_monkey_enabled:

