version: '3'
services:
  rabbit:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
#  eureka:
#    image: "springcloud/eureka"
#    ports:
#      - "8761:8761"

  order-service:
    build: ./eda-order-service
    image: eda-order-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
#      - eureka
    environment:
      spring.rabbitmq.host: rabbit

  reservation-service:
    build: ./eda-reservation-service
    image: eda-reservation-service:latest
    ports:
      - "8081:8080"
    depends_on:
      - rabbit
#      - eureka
    environment:
      spring.rabbitmq.host: rabbit

  payment-service:
    build: ./eda-payment-service
    image: eda-payment-service:latest
    ports:
    - "8082:8080"
    depends_on:
    - rabbit
    #      - eureka
    environment:
      spring.rabbitmq.host: rabbit

