POST http://localhost:8080/orders
content-type: application/json
accept: application/json

{
  "showId":"456765",
  "seats":["1A","1B","1C"]
}

###

GET http://localhost:8080/orders/41aa180a-c3b1-4e81-a1d1-2f3af5f8b48b
accept: application/json


###
POST http://localhost:8080/payments/accept
content-type: application/json
accept: application/json

{
  "orderId":"41aa180a-c3b1-4e81-a1d1-2f3af5f8b48b",
  "showId":"456765"
}

###
POST http://localhost:8080/seats/reserve
content-type: application/json
accept: application/json

{
  "orderId":"41aa180a-c3b1-4e81-a1d1-2f3af5f8b48b",
  "showId":"456765",
  "seats":["1A","1B","1C"]
}

###

POST http://localhost:8080/reservations/41aa180a-c3b1-4e81-a1d1-2f3af5f8b48b/complete
accept: application/json


###

GET http://localhost:8080/reservations/00001
accept: application/json


###
POST http://localhost:8080/orders/sync
content-type: application/json
accept: application/json

{
  "showId":"456765",
  "status":"pending",
  "seats":["1A","1B","1C"]
}

###

GET http://localhost:8080/orders/counts
accept: application/json

###
