kind: ConfigMap
apiVersion: v1
data:
  hazelcast-order.xml: "<hazelcast xmlns=\"http://www.hazelcast.com/schema/config\">\r\n
    \   <group>\r\n        <name>order-service-cache</name>\r\n    </group>\r\n</hazelcast>\r\n"
  hazelcast-reservation.xml: "<hazelcast xmlns=\"http://www.hazelcast.com/schema/config\">\r\n
    \   <group>\r\n        <name>reservation-service-cache</name>\r\n    </group>\r\n</hazelcast>\r\n"
metadata:
  name: hazelcast-config
