kind: Service
apiVersion: v1
metadata:
  name: order-service
  labels:
    sample: eda
spec:
  type: LoadBalancer
  selector:
    app: order-workload
  ports:
    - name: http
      targetPort: server-port
      port: 8080

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-workload
  labels:
    sample: eda
    class: workload
spec:
  selector:
    matchLabels:
      app: order-workload
  replicas: 1
  template:
    metadata:
      labels:
        app: order-workload
        sample: eda
        class: workload
      annotations:
        recycle-trigger: "20181224"
    spec:
      containers:
        - name: order-workload
          image: eda-order-service:1
          ports:
            - name: server-port
              containerPort: 8080
          env:
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: app_services_payment
              value: http://payment-service
            - name: app_services_reservation
              value: http://reservation-service
            - name: chaos_monkey_enabled
              valueFrom:
                configMapKeyRef:
                  key: chaos.monkey.enabled
                  name: eda-config
