kind: Service
apiVersion: v1
metadata:
  name: payment-service
  labels:
    sample: eda
spec:
  type: ClusterIP
  selector:
    app: payment-workload
  ports:
    - name: http
      targetPort: server-port
      port: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment-workload
  labels:
    sample: eda
    class: workload
spec:
  selector:
    matchLabels:
      app: payment-workload
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-workload
        sample: eda
        class: workload
      annotations:
        recycle-trigger: "20181224"
    spec:
      containers:
        - name: payment-workload
          image: eda-payment-service:1
          ports:
            - name: server-port
              containerPort: 8080
          env:
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: chaos.monkey.assaults.level
              value: 10 # attack each 10th request. the default is 5
            - name: chaos_monkey_enabled
              valueFrom:
                configMapKeyRef:
                  key: chaos.monkey.enabled
                  name: eda-config
