kind: Service
apiVersion: v1
metadata:
  name: payment-service
  labels:
    sample: eda
spec:
  type: ClusterIP
  selector:
    app: payment-workload
  ports:
    - name: http
      targetPort: server-port
      port: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment-workload
  labels:
    sample: eda
spec:
  selector:
    matchLabels:
      app: payment-workload
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-workload
        sample: eda
    spec:
      containers:
        - name: payment-workload
          image: eda-payment-service:1
          ports:
            - name: server-port
              containerPort: 8080
          env:
            - name: spring.rabbitmq.host
              value: rabbitmq
