server:
  error:
    whitelabel:
      enabled: false


spring:
  profiles:
    active: rabbitmq
  application:
    name: eda-order
  cloud:
    function:
      definition: seatEventProcessor
    stream:
      bindings:
        seatEventProcessor-in-0:
          destination: ticketing-event
          group: order-processor
        orderPublisher-out-0:
          destination: ticketing-event


app:
  services:
    payment: http://eda-payment
    reservation: http://eda-reservation


---
# the destination is the RMQ exchange while the group is the RMQ queue
spring:
  config:
    activate:
      on-profile: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      default-binder: rabbit
      rabbit:
        bindings:
          seatEventProcessor-in-0:
            consumer:
              binding-routing-key: ticketing.seats.assigned.v1
          orderPublisher-out-0:
            producer:
              routing-key-expression: headers['message-type']



