server:
  error:
    whitelabel:
      enabled: false


spring:
  profiles:
    active: rabbitmq
  application:
    name: eda-order
  cloud:
    function:
      definition: seatEventProcessor
    stream:
      bindings:
        seatEventProcessor-in-0:
          destination: seats-events
          group: order-processor
        orderPublisher-out-0:
          destination: order-events

    # disable azure servicebus
    azure:
      servicebus:
        enabled: false

app:
  services:
    payment: http://eda-payment
    reservation: http://eda-reservation


---
# the destination is the RMQ exchange while the group is the RMQ queue
spring:
  config:
    activate:
      on-profile: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      default-binder: rabbit

---
# the destination is the Azure Servicebus Topic and the group is the Subscription
# binder properties: https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-stream-binder/spring-cloud-azure-servicebus-topic-stream-binder
spring:
  config:
    activate:
      on-profile: azure-topic
  cloud:
    stream:
      servicebus:
        topic:
          bindings:
            orderProcessor-in-0:
              consumer:
                checkpoint-mode: RECORD
      default-binder: servicebus-topic
    azure:
      servicebus:
        enabled: true
        connection-string:


