spring:
  profiles:
    active: chaos-monkey
  application:
    name: eda-order
  cloud:
    stream:
      rabbit:
        bindings:
          output:
            producer:
              # configure spring cloud stream to use the value of the topic header
              # on the message as the topic when publishing.
              routingKeyExpression: 'headers["topic"]'

      # the destination is the RMQ exchange while the group is the RMQ queue
      bindings:
        input:
          destination: ticketing-events
          group: order-processor
          binder: local_rabbit
        output:
          destination: ticketing-events
          binder: local_rabbit

      binders:
        local_rabbit:
          type: rabbit

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

app:
  services:
    payment:
      host: localhost
      port: 8081
    reservation:
      host: localhost
      port: 8082

chaos:
  monkey:
    enabled: false
    assaults:
      exceptions-active: false
      kill-application-active: false
      latency-active: true
    watcher:
      component: true
      repository: true
      rest-controller: true
      service: true
