server:
  error:
    whitelabel:
      enabled: false

chaos:
  monkey:
    enabled: false
    assaults:
      exceptions-active: false
      kill-application-active: true
      latency-active: true
    watcher:
      component: false
      repository: true
      rest-controller: true
      service: true

spring:
  profiles:
    active: chaos-monkey
  application:
    name: eda-payment
  cloud:
    stream:
      # the destination is the RMQ exchange while the group is the RMQ queue
      bindings:
        input:
          destination: ticketing-events
          group: payment-processor
        output:
          destination: ticketing-events

    # disable azure servicebus
    azure:
      servicebus:
        enabled: false

---
spring:
  profiles: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      default-binder: rabbit

---
# the destination is the Azure Servicebus Topic and the group is the Subscription
# binder properties: https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-stream-binder/spring-cloud-azure-servicebus-topic-stream-binder
spring:
  profiles: azure-topic
  cloud:
    stream:
      servicebus:
        topic:
          bindings:
            input:
              consumer:
                checkpoint-mode: RECORD
      default-binder: servicebus-topic
    azure:
      servicebus:
        enabled: true
        connection-string:
