server:
  error:
    whitelabel:
      enabled: false

chaos:
  monkey:
    enabled: false
    assaults:
      exceptionsActive: true
      latency-active: true
      # the kill-application assult has to be false in order for the demo to work correctly.
      # this service stores state between calls using a transient cache
      kill-application-active: false
    watcher:
      service: true
      repository: true
      rest-controller: true
      component: false

spring:
  profiles:
    active: chaos-monkey, rabbitmq
  application:
    name: eda-reservation
  cloud:
    stream:
      # the destination is the RMQ exchange while the group is the RMQ queue
      bindings:
        input:
          destination: ticketing-events
          group: reservations-processor
        output:
          destination: ticketing-events

    # disable azure servicebus
    azure:
      servicebus:
        enabled: false

app:
  services:
    payment: http://eda-payment
    reservation: http://eda-reservation

---
# the destination is the RMQ exchange while the group is the RMQ queue
spring:
  profiles: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      default-binder: rabbit

---
# the destination is the Azure Servicebus Topic and the group is the Subscription
# binder properties: https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-stream-binder/spring-cloud-azure-servicebus-topic-stream-binder
spring:
  profiles: azure-topic
  cloud:
    stream:
      servicebus:
        topic:
          bindings:
            input:
              consumer:
                checkpoint-mode: RECORD
      default-binder: servicebus-topic
    azure:
      servicebus:
        enabled: true
        connection-string:
