chaos:
  monkey:
    enabled: false
    assaults:
      latency-active: true
      kill-application-active: true
    watcher:
      service: true
      repository: true
      rest-controller: true
      component: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  profiles:
    active: chaos-monkey
  application:
    name: eda-reservation
  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: ticketing.#
          output:
            producer:
              # configure spring cloud stream to use the value of the topic header
              # on the message as the topic when publishing.
              routingKeyExpression: 'headers["topic"]'

      # the destination is the RMQ exchange while the group is the RMQ queue
      bindings:
        input:
          destination: ticketing-events
          group: reservations-processor
          binder: local_rabbit
        output:
          destination: ticketing-events
          binder: local_rabbit

      binders:
        local_rabbit:
          type: rabbit

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

