server:
  error:
    whitelabel:
      enabled: false

chaos:
  monkey:
    enabled: false
    assaults:
      exceptionsActive: true
      latency-active: true
      # the kill-application assult has to be false in order for the demo to work correctly.
      # this service stores state between calls using a transient cache
      kill-application-active: false
    watcher:
      service: true
      repository: true
      rest-controller: true
      component: false

spring:
  profiles:
    active: chaos-monkey
  application:
    name: eda-reservation
  cloud:
    stream:
      # the destination is the RMQ exchange while the group is the RMQ queue
      bindings:
        input:
          destination: ticketing-events
          group: reservations-processor
          binder: local_rabbit
        output:
          destination: ticketing-events
          binder: local_rabbit

      binders:
        local_rabbit:
          type: rabbit

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

