server:
  error:
    whitelabel:
      enabled: false


spring:
  profiles:
    active: rabbitmq
  application:
    name: eda-reservation
  cloud:
    function:
      definition: reservationProcessor
    stream:
      # the destination is the RMQ exchange while the group is the RMQ queue
      bindings:
        reservationProcessor-in-0:
          destination: ticketing-events
          group: reservations-processor
        reservationPublisher-out-0:
          destination: ticketing-events

    # disable azure servicebus
    azure:
      servicebus:
        enabled: false

app:
  services:
    payment: http://eda-payment
    reservation: http://eda-reservation

---
# the destination is the RMQ exchange while the group is the RMQ queue
spring:
  profiles: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      default-binder: rabbit

---
# the destination is the Azure Servicebus Topic and the group is the Subscription
# binder properties: https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-stream-binder/spring-cloud-azure-servicebus-topic-stream-binder
spring:
  profiles: azure-topic
  cloud:
    stream:
      servicebus:
        topic:
          bindings:
            reservationProcessor-in-0:
              consumer:
                checkpoint-mode: RECORD
      default-binder: servicebus-topic
    azure:
      servicebus:
        enabled: true
        connection-string:
